### ISSUE TITLE
Switch from Apache to nginx

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/leverage#18]
Since we run our own webserver, it could be worthwhile to use a modern, high-performance server.

**Comment by ub1quit33** [comment]
The nginx config has been placed in /usr/local/etc (in order to store it in a directory we can keep under version control) and has been configured to serve the static resources under /var/www/leverage.com/static/ from the /static/ URI.

AFAIK, no WSGI backend has been decided on or configured, so we'll obviously have to hold that discussion before I can configure nginx to serve requests to the application stack.

**Comment by ub1quit33** [comment]
After discusing with @BayoAdejare, sounds like Gunicorn was initially chosen in order to satisfy a rapid deployment, but with more time on our hands it should be feasible to configure uWSGI for a more powerful backend instead.

**Comment by ub1quit33** [comment]
Just noticed that nginx is running 4 worker processes... since we only have 1 CPU on the server, I dropped that down to 1.

**Comment by ub1quit33** [comment]
Uploaded the configs to a [new repository](https://github.com/Lever-age/infra); uwsgi has been configured as of [273a60](https://github.com/Lever-age/infra/commit/273a6076e33db56591dd6ee76d4ee74c9753dd8d) and enabled via nginx config in [f686a7](https://github.com/Lever-age/infra/commit/f686a7c89da0cc4454fb607ab5d58b940a28e069).

You can now view the running application on the server by pointing your local hosts file to the server's IP address.

**Comment by ub1quit33** [comment]
This item is ready for review

**Comment by ub1quit33** [comment]
Final note-- uWSGI is currently configured to run 5 workers.. I configured that number as a "for now" value, which I presume we'll want to tune further before turning this app loose for the public.

**Comment by lottspot** [comment]
This is long done
